import React from "react";

export const metadata = {
  title: "Installation Page | PH Play Store",
  description: "Generated by create next app",
};

const page = () => {
  return <div>installation page</div>;
};

export default page;
