import TrendingApps from "@/components/homepage/TrendingApps";
import React from "react";

export const metadata = {
  title: "Apps Page | PH Play Store",
  description: "Generated by create next app",
};

const AppsPage = () => {
  return (
    <div>
      <TrendingApps />
    </div>
  );
};

export default page;
